do
joyapisi/ThePortfolio pull request #10
Opened 2023-03-06 11:17 UTC by joyapisi

2023-03-06 19:47 UTC, huseyinbiyik commented
Hi team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that has a templated text on your README, kindly remove it.
<img width="701" alt="Screenshot 2023-03-06 at 10 46 38 PM" src="https://user-images.githubusercontent.com/25887253/223214921-0838c385-36a5-42a7-aea8-5edca6a717e5.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-06 21:00 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- New linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
- Kindly add some space before the header like on the Figma template.
<img width="428" alt="Screenshot 2023-03-06 at 11 47 11 PM" src="https://user-images.githubusercontent.com/25887253/223227126-49a1cf15-8c91-4878-b4a2-5f93d8bc1968.png">
<img width="428" alt="Screenshot 2023-03-06 at 11 47 35 PM" src="https://user-images.githubusercontent.com/25887253/223227131-34695bf5-14f2-47cd-b7b8-f1026504d379.png">

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 21:00 UTC, huseyinbiyik commented on style.css
> +#navigationList {
Good job with the background blur, it looks fantastic 👌  But let's make sure when the user clicks on the menu link, the menu closes.
<img width="763" alt="Screenshot 2023-03-06 at 11 43 38 PM" src="https://user-images.githubusercontent.com/25887253/223227559-a4d74b94-77f7-455d-a640-d6af53c75df6.png">
![Screen Recording 2023-03-06 at 11 41 36 PM](https://user-images.githubusercontent.com/25887253/223227601-c899224a-6850-461f-999c-ec8235f1466a.gif)

2023-03-07 10:49 UTC, KayLemba approved these changes
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @TEAM      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯 
- [x] Nice UI design. 🥇 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

2023-03-07 10:56 UTC, merged